# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1068, 790)
        main_window.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.toggle_layout = QtWidgets.QHBoxLayout()
        self.toggle_layout.setObjectName("toggle_layout")
        self.verticalLayout.addLayout(self.toggle_layout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.season_label = QtWidgets.QLabel(self.centralwidget)
        self.season_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.season_label.setObjectName("season_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.season_label)
        self.season_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.season_combo_box.setObjectName("season_combo_box")
        self.season_combo_box.addItem("")
        self.season_combo_box.addItem("")
        self.season_combo_box.addItem("")
        self.season_combo_box.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.season_combo_box)
        self.day_label = QtWidgets.QLabel(self.centralwidget)
        self.day_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.day_label.setObjectName("day_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.day_label)
        self.day_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.day_spin_box.setMinimum(1)
        self.day_spin_box.setMaximum(28)
        self.day_spin_box.setObjectName("day_spin_box")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.day_spin_box)
        self.fertilizer_label = QtWidgets.QLabel(self.centralwidget)
        self.fertilizer_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fertilizer_label.setObjectName("fertilizer_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fertilizer_label)
        self.fertilizer_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.fertilizer_combo_box.setObjectName("fertilizer_combo_box")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fertilizer_combo_box)
        self.verticalLayout.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.crop_table_view = QtWidgets.QTableView(self.centralwidget)
        self.crop_table_view.setObjectName("crop_table_view")
        self.crop_table_view.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.crop_table_view)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Stardew Crop Calculator"))
        self.season_label.setText(_translate("main_window", "Season:"))
        self.season_combo_box.setItemText(0, _translate("main_window", "Winter"))
        self.season_combo_box.setItemText(1, _translate("main_window", "Spring"))
        self.season_combo_box.setItemText(2, _translate("main_window", "Summer"))
        self.season_combo_box.setItemText(3, _translate("main_window", "Fall"))
        self.day_label.setText(_translate("main_window", "Day:"))
        self.fertilizer_label.setText(_translate("main_window", "Fertilizer:"))
